name: jeb_ui
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  shared_preferences:
  printing:
  pdf:
  share_plus:
  sqflite:
  path_provider:
  material_design_icons_flutter:
  line_awesome_flutter:
  provider:
  dartz:
  url_launcher:
  cupertino_icons: ^1.0.8
  intl_phone_number_input:
  local_auth:
  internet_connection_checker_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  generate: true # Enable generation of localization files
  # Localizations source
  # By default, Flutter uses lib/l10n/ for ARB files generated to dart via flutter_gen

  assets:
    - assets/images/jaiblogo.png
    - assets/images/logo.png

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
